INSERT INTO caseload (
    grouped_date,
    unique_device_wearer_id,
    first_name,
    last_name,
    date_of_birth,
    house_number_and_street_name,
    city_or_town,
    county,
    country,
    postcode,
    nomis_id,
    pnc_id,
    delius_id,
    mdss_person_id,
    order_id,
    order_start_date,
    order_commencement_date,
    order_end_date,
    order_type,
    order_type_description,
    order_type_detail,
    responsible_organisation,
    responsible_officer_name,
    is_monitored,
    enforceable_condition,
    __datetime_added
)
VALUES (
    TIMESTAMP '2025-10-01 00:00:00.000000',
    'DEVWR00000068',
    'Test',
    'Person',
    DATE '1990-05-28',
    'Test Street',
    'London',
    'Greater London',
    'United Kingdom',
    'SW1 1WS',
    NULL,
    NULL,
    'X972696',
    10002,
    'MON10000067',
    TIMESTAMP '2025-09-29 14:15:00.000000',
    NULL,
    TIMESTAMP '2033-09-29 14:15:02.000000',
    'post_release',
    'hdc',
    NULL,
    'Probation London Licences',
    NULL,
    FALSE,
    'location_monitoring',
    CAST(current_date AS timestamp)
);