---
# Per environment values which override defaults in hmpps-electronic-monitoring-data-insights-api/values.yaml

generic-service:
  serviceAccountName: "hmpps-em-data-insights-prod"

  ingress:
    host: electronic-monitoring-data-insights-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PROBATION_SEARCH_API_URL: "https://probation-offender-search.hmpps.service.justice.gov.uk"
    UI_SERVICE_BASE_URL: "https://electronic-monitoring-data-insights-ui.hmpps.service.justice.gov.uk"
    SERVICE_BASE_URL: "https://electronic-monitoring-data-insights-api.hmpps.service.justice.gov.uk"
    MFA_REQUIRED: "false"
    ROW_LIMIT: 1000
    MDSS_DB: "data_insights"
    FMS_DB: "serco_fms_curated_dev_dbt"
    ATHENA_OUTPUT_BUCKET: "s3://emds-prod-athena-query-results-20240918073115959600000002/output"
    WORKGROUP: "976799291502-default"
    RESPONSIBLE_ORGANISATIONS: "Probation London Community/Suspended Sentence,Probation London Licences"

generic-prometheus-alerts:
  alertSeverity: hmpps-electronic-monitoring-data-insights-prod
