---
# Per environment values which override defaults in hmpps-electronic-monitoring-data-insights-api/values.yaml

generic-service:
  replicaCount: 2

  serviceAccountName: "hmpps-em-data-insights-preprod"

  ingress:
    host: electronic-monitoring-data-insights-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MFA_REQUIRED: "false"
    ROW_LIMIT: 1000
    MDSS_DB: "data_insights_preprod_dbt"
    FMS_DB: "serco_fms_curated_dev_dbt"
    ATHENA_OUTPUT_BUCKET: "emds-preprod-athena-query-results-20241105110923178000000003"
    WORKGROUP: "443370694497-default"

generic-prometheus-alerts:
  alertSeverity: hmpps-electronic-monitoring-data-insights-preprod
