---
# Per environment values which override defaults in hmpps-electronic-monitoring-data-insights-api/values.yaml

generic-service:
  replicaCount: 2

  serviceAccountName: "hmpps-em-data-insights-prod"

  ingress:
    host: electronic-monitoring-data-insights-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    UI_SERVICE_BASE_URL: "https://electronic-monitoring-data-insights-ui.hmpps.service.justice.gov.uk"
    SERVICE_BASE_URL: "https://electronic-monitoring-data-insights-api.hmpps.service.justice.gov.uk"
    MFA_REQUIRED: "false"
    ROW_LIMIT: 1000
    MDSS_DB: "staged_mdss_dev_dbt"
    FMS_DB: "serco_fms_curated_dev_dbt"
    ATHENA_OUTPUT_BUCKET: "s3://emds-dev-athena-query-results-20240917144028307600000004/output"
    WORKGROUP: "800964199911_default"

generic-prometheus-alerts:
  alertSeverity: hmpps-electronic-monitoring-data-insights-prod
